### ISSUE TITLE
Replace native-tls with reactls

### ISSUE THREAD

**Issue by himanshumps** [lnx-search/rewrk#28]
I think we will have issues while building musl due to openssl dependency on native-tls. 

Please let me know and I can work on replacing it.

I do agree that we will lose support for older cipher suites.

**Comment by ChillFish8** [comment]
Im not sure what you mean? We seem to be compiling fine via musl. If it *does* start to cause issues I'm down to change it but for now I think this is a non-issue. We build nightly on musl so it that should give a pretty good warning sign if anything is broken.

**Comment by kkocdko** [comment]
[rewrk-b54aede-x86_64-unknown-linux-musl.zip](https://github.com/ChillFish8/rewrk/files/9163439/rewrk-b54aede-x86_64-unknown-linux-musl.zip)

```toml
# Cargo.toml
[dependencies]
openssl = { version = "0.10", features = ["vendored"] }
[profile.release]
strip = true
lto = "fat"
# and run `cargo zigbuild --release --target=x86_64-unknown-linux-musl`
```
